FROM nginx:latest
COPY ./deployment/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./deployment/nginx/vhost.conf /etc/nginx/conf.d/default.conf
COPY ./deployment/nginx/entrypoint.sh /entrypoint.sh
COPY . /var/www/html
RUN rm -rf /var/www/html/deployment && chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
