apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: football-api-assets-volume-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard