apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: football-api-assets-shared-vc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client