{
 "title": "Football API business metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(footballapi_current_requests{application=\"football-api\"},environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(footballapi_requests_latency_milliseconds_bucket{application=\"football-api\"},project)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\"}[1m]))"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(footballapi_requests_latency_milliseconds_sum{application=\"football-api\", environment=\"$environment\", project=\"$project\"}[1m])) * 0.001 /\nsum(rate(footballapi_requests_latency_milliseconds_count{application=\"football-api\", environment=\"$environment\", project=\"$project\"}[1m]))"
    }
   ]
  },
  {
   "title": "Write requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", method=\"POST\", route=~\".+\"})",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", method=\"PATCH\", route=~\".+\"})",
     "legendFormat": "PATCH"
    },
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", method=\"DELETE\", route=~\".+\"})",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Read requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", method=\"GET\", route=~\".+\"})",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Exceptions by status code",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", status_code=~\"4..\", route=~\".+\"})",
     "legendFormat": "4**"
    },
    {
     "expr": "sum(footballapi_requests_total{application=\"football-api\", environment=\"$environment\", project=\"$project\", status_code=~\"5..\", route=~\".+\"})",
     "legendFormat": "5**"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(footballapi_requests_total{project=\"$project\", application=\"football-api\", environment=\"$environment\", method=~\".+\"})",
     "legendFormat": "Total request number"
    }
   ]
  },
  {
   "title": "Average response size (kB) per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(footballapi_response_body_size_sum{application=\"football-api\", environment=\"$environment\", project=\"$project\"}[1m]))  /\nsum(rate(footballapi_response_body_size_count{application=\"football-api\", environment=\"$environment\", project=\"$project\"}[1m])) * 0.001"
    }
   ]
  },
  {
   "title": "Total egress MB sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(footballapi_response_body_size_sum{application=\"football-api\", environment=\"$environment\", project=\"$project\", route=~\".+\"}) *  0.000001"
    }
   ]
  }
 ]
}